name: Trumbowyg
version: 1.0.0
description: Light, translatable and customisable WYSIWYG editor for Flextype.
icon:
  name: flag
  set: bootstrap
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/trumbowyg
bugs: https://github.com/flextype-plugins/trumbowyg/issues
license: MIT

dependencies:
  flextype: 0.9.16
  twig: '>=2.0.0'
  blueprints: '>=1.0.0'
